config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: :omniauth_callbacks
  }
  root controller: :recipes, action: :index
  resources :recipes, only: [:index, :show]
  resources :charges, only: [:new, :create]
  resources :membership, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/membership.rb
class Membership < ApplicationRecord
  validates :title, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw-info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @membership = Membership.find(params[:id])
  end

  def create
    membership = Membership.find(params[:membership_id]) 
  end
end

app/controllers/membership_controller.rb
class MembershipController < ApplicationController
  def index
    @memberships = Membership.all 
  end

  def show
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_date'] = request.env['ominauth.auth']
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = FoodService.get_recipes(params[:search])
  end

  def show
    @recipe = FoodService.get_ingredients(params[:id])
  end

  private
  def recipe_params
    params.require(:recipe).permit(:search)
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charges/create.html.haml
%h1 Charges#create
%p Find me in app/views/charges/create.html.haml

app/views/charges/new.html.haml
%h1 Payment form for #{@membership.title} Members!
= form_with url: charges_path, local: true, method: :post, id: :charge_form do |form|
  = form.hidden_field :membership_id, value: @membership.id
  = form.label :email
  = form.text_field :email
  #card-number
  #card-expiry
  #card-cvc
  = form.submit 'Submit Payment'

app/views/layouts/_nav.html.haml
%nav
  - if user_signed_in?
    Logged in as 
    = succeed "." do 
      %strong= current_user.email 
    \#{link_to 'Logout', destroy_user_session_path, method: :delete, class: 'navbar-link'}
  - else 
    = link_to "Sign up here", new_user_registration_path, class: 'navbar-link'
    \#{link_to "Login", new_user_session_path, class: 'navbar-link'}
    \#{link_to 'Login with Facebook', user_facebook_omniauth_authorize_path, class: 'navbar-link'}

app/views/layouts/application.html.haml
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Foodapp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/nav'
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/membership/index.html.haml
%h1 Membership#index
%p Find me in app/views/membership/index.html.haml

%div
  - @memberships.each do |membership|
    %div
      = membership.title
      = link_to "Buy", new_charge_path(id: membership.id)
   

-# Soluton to find Premium using bindingPry, doesn't work with tests though.
-# %div
-# - @memberships.each do |iteration|
-#   - @memberships.find_by_id(1)
-#   = @memberships[0].title
-#   = link_to "Buy", new_charge_path(id: @memberships[0].id)

-# {id: "#{dom_id(membership.id)}"}

app/views/membership/show.html.haml
%h1 Membership#show
%p Find me in app/views/membership/show.html.haml

app/views/recipes/index.html.haml
.card-container
  .card.u-clearfix
    .card-body
    %h1 Let's Cook!
    %img.w-full{src: "https://magnolia.com/wp-content/uploads/2017/12/image4-1.png", alt: "No image to display"}
    %h2 Choose from a list of recipes based on what you already have at home.
    %h4 What's in your fridge?
    %p 
    = form_tag(recipes_path, method: :get) do
      = text_field_tag(:search, params[:search], placeholder: "Search")
      = submit_tag ("Submit")
    - if @recipes.nil?
      %p Please search for ingredient
    - elsif @recipes == 'error'
      %p There is no recipe with that ingredient
    - else
      - @recipes.each do |recipe|
        %h3.subtle
          = link_to recipe["title"], recipe_path(recipe['id'], title: recipe['title'])

app/views/recipes/show.html.haml
.card-container
  .card.u-clearfix
    .card-body
    %h1.card-title= @recipe['title']
    %img.card-media{src: @recipe['image'], alt: "No image to display"}
    %p 
    .card-read Recipe
    - if @recipe['analyzedInstructions'] == []
      %span.card-description.subtle There is no intructions for this item
    - else
      - @recipe['analyzedInstructions'].each do |instruction|
        - instruction['steps'].each do |step|
          %li
            %span.card-description.subtle= step['step']
            %p
    = link_to 'Back', root_path
    %p 
    .card-shadow